### ISSUE TITLE
test script

### ISSUE THREAD

**Issue by 502463708** [isyangshu/Surgformer#6]
when I tried to infer a trained model using sh scripts/test.sh, I found that it is actually calling run_phase_training.py, which is the same with scripts/train.sh. So I am not sure whether it is right? How can I infer a trained model? Thanks!

CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch \
--nproc_per_node=2 \
--master_port 12326 \
downstream_phase/run_phase_training.py \
--batch_size 32 \
--epochs 50 \

**Comment by isyangshu** [comment]
Yes, you can directly use sh scripts/test.sh with --eval and --finetune your-parameter-path.
Since we can directly do reference in https://github.com/isyangshu/Surgformer/blob/master/downstream_phase/run_phase_training.py#L813.

**Comment by 502463708** [comment]
I got it, thanks~
